### ISSUE TITLE
Hide console window

### ISSUE THREAD

**Issue by arthniwa** [kampffrosch94/jpdb-connect#13]
Thank you for this script.

Is it possible to not keep the console window open while using it? Some scripts I know have something like a "--no-console" command.

**Comment by kampffrosch94** [comment]
Not really sure why you would want that.
The output has to go somewhere, in case something goes wrong. Or just to double check that everything works alright.

**Comment by sdbversini** [comment]
If you're on linux, you can create a systemd service(what I did), or use like `nohup ./jpdb-connect &` or something.

On windows, there are tools to create services like https://nssm.cc/usage, I haven't tested it out but it should work.
No idea about macos but surely something like that should exist for it.

I think more than editing the program, it would make more sense to make a wiki page about these tricks for people who desire, it's definitely important to have the logs at first for the user, so that they learn how to get the program set up.

**Comment by kampffrosch94** [comment]
Yeah this looks like more trouble than it is worth.
I might look into minimizing to tray if I ever bother to turn this into a gui program,
but I'll leave it as is for now.
